
source ../scripts/adi_env.tcl
source $ad_hdl_dir/projects/scripts/adi_project.tcl
source $ad_hdl_dir/projects/scripts/adi_board.tcl

set p_device "xc7z010clg225-1"
adi_project_xilinx pluto

adi_project_files pluto [list \
  "system_top.v" \
  "system_constr.xdc" \
  "$ad_hdl_dir/library/xilinx/common/ad_iobuf.v" \
  "$ad_hdl_dir/library/ettus-fpga/e310/e310_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/e310/e310_io.v" \
  "$ad_hdl_dir/library/ettus-fpga/e310/ppsloop.v" \
  "$ad_hdl_dir/library/ettus-fpga/ip/dds_sin_cos_lut_only/dds_sin_cos_lut_only.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/complex_multiplier/complex_multiplier.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/divide_int16_int32/divide_int16_int32.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/cordic_rotator/cordic_rotator.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/complex_to_magphase/complex_to_magphase.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/complex_multiplier_dds/complex_multiplier_dds.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/axi_hb47/axi_hb47.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/divide_int32/divide_int32.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/cordic_rotate_int24/cordic_rotate_int24.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/axi_hb31/axi_hb31.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/divide_int16/divide_int16.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/divide_uint32/divide_uint32.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/complex_to_magphase_int32/complex_to_magphase_int32.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/cordic_rotator24/cordic_rotator24.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/divide_int24/divide_int24.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/complex_to_magphase_int16_int24/complex_to_magphase_int16_int24.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/dds/dds.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/cordic_rotate_int24_int16/cordic_rotate_int24_int16.xci" \
  "$ad_hdl_dir/library/ettus-fpga/ip/axi_fft/axi_fft.xci" \
  "$ad_hdl_dir/library/ettus-fpga/e310/fifo_short_2clk/fifo_short_2clk.xci" \
  "$ad_hdl_dir/library/ettus-fpga/e310/fifo_4k_2clk/fifo_4k_2clk.xci" \
  "$ad_hdl_dir/library/ettus-fpga/control/axi_crossbar.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/serial_to_settings.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/filter_bad_sid.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axi_fifo_header.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axi_test_vfifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axil_to_ni_regport.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/gpio_atr.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/pulse_synchronizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/ram_2port.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/pulse_stretch.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/priority_encoder.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/radio_ctrl_proc.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axil_regport_master.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/synchronizer_impl.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axi_setting_reg.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/simple_spi_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/regport_to_xbar_settingsbus.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/reset_sync.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/por_gen.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/gpio_atr_io.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axi_slave_mux.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/settings_bus_mux.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/regport_resp_mux.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/bin2gray.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axi_crossbar_regport.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/binary_encoder.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/axi_forwarding_cam.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/arb_qualify_master.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/regport_to_settingsbus.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/s7_icap_wb.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/map/cam_priority_encoder.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/map/cam_bram.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/map/cam_srl.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/map/axis_muxed_kv_map.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/map/kv_map.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/map/cam.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/ad5662_auto_spi.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/gray2bin.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/settings_bus_timed_2clk.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/user_settings.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/synchronizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/priority_encoder_one_hot.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/simple_i2c_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/mdio_master.v" \
  "$ad_hdl_dir/library/ettus-fpga/control/setting_reg.v" \
  "$ad_hdl_dir/library/ettus-fpga/gpif2/gpif2_error_checker.v" \
  "$ad_hdl_dir/library/ettus-fpga/gpif2/fifo64_to_gpif2.v" \
  "$ad_hdl_dir/library/ettus-fpga/gpif2/gpif2_slave_fifo32.v" \
  "$ad_hdl_dir/library/ettus-fpga/gpif2/gpif2_to_fifo64.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio_200/radio_legacy.v" \
  "$ad_hdl_dir/library/ettus-fpga/timing/pps_generator.v" \
  "$ad_hdl_dir/library/ettus-fpga/timing/timekeeper.v" \
  "$ad_hdl_dir/library/ettus-fpga/timing/time_compare.v" \
  "$ad_hdl_dir/library/ettus-fpga/timing/pps_synchronizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/include/utils.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/include/defines.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/include/timescale.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/include/CRC32_D8.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/include/CRC32_D64.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/tx_checker.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/rx_data_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/rx_dequeue.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/generic_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/xge_mac.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/meta_sync.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/sync_clk_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/utils.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/tx_data_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/generic_mem_xilinx_block.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/sync_clk_wb.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/tx_enqueue.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/xge_mac_wb.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/wishbone_if.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/generic_fifo_ctrl.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/defines.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/tx_hold_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/meta_sync_single.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/generic_mem_medium.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/tx_dequeue.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/sync_clk_xgmii_tx.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/generic_mem_small.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/rx_checker.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/rx_enqueue.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/timescale.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/fault_sm.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/CRC32_D8.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/rx_hold_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge/rtl/verilog/CRC32_D64.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/LvFpga_Chinch_Interface.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/pcie_wb_reg_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/pcie_pkt_route_specifier.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/pcie_lossy_samp_gate.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/pcie_axi_wb_conv.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/data_swapper_64.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/ioport2_msg_codec.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/pcie_dma_ctrl.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/pcie_basic_regs.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/pcie_iop2_msg_arbiter.v" \
  "$ad_hdl_dir/library/ettus-fpga/e310/e310_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/vrlp/vrlp_eth_framer.v" \
  "$ad_hdl_dir/library/ettus-fpga/vrlp/compressed_vita_to_vrlp.v" \
  "$ad_hdl_dir/library/ettus-fpga/vrlp/vrlp_to_compressed_vita.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/eth_interface.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/cvita_dechunker.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/cvita_to_axis.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/source_flow_control.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/cvita_chunker.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/cvita_dest_lookup.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/axis_to_cvita.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/vita_eth_framer.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/eth_dispatch.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/chdr_eth_framer.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/ip_hdr_checksum.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/fix_short_packet.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/cvita_insert_tlast.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/axis_packet_debug.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/arm_deframer.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc/cvita_packet_debug.v" \
  "$ad_hdl_dir/library/ettus-fpga/coregen/simple_fir.v" \
  "$ad_hdl_dir/library/ettus-fpga/coregen/divide_int32.v" \
  "$ad_hdl_dir/library/ettus-fpga/coregen/streaming_fft.v" \
  "$ad_hdl_dir/library/ettus-fpga/coregen/complex_to_magphase.v" \
  "$ad_hdl_dir/library/ettus-fpga/coregen/simple_fft.v" \
  "$ad_hdl_dir/library/ettus-fpga/coregen/cordic_rotator.v" \
  "$ad_hdl_dir/library/ettus-fpga/coregen/complex_multiplier.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/strobed_to_axi.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_dma_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_defs.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_chdr_header_trigger.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_add_preamble.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_strip_preamble.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_dummy.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_to_strobed.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_fast_extract_tlast.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_replay.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_chdr_test_pattern.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_embed_tlast.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_fast_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/crc_xnor.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_extract_tlast.v" \
  "$ad_hdl_dir/library/ettus-fpga/axi/axi_dma_master.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo_200/axi_fifo_legacy.v" \
  "$ad_hdl_dir/library/ettus-fpga/zynq_fifo/zf_arbiter.v" \
  "$ad_hdl_dir/library/ettus-fpga/zynq_fifo/zf_stream_to_host.v" \
  "$ad_hdl_dir/library/ettus-fpga/zynq_fifo/zynq_fifo_top.v" \
  "$ad_hdl_dir/library/ettus-fpga/zynq_fifo/zf_slave_settings.v" \
  "$ad_hdl_dir/library/ettus-fpga/zynq_fifo/zf_slave_readback.v" \
  "$ad_hdl_dir/library/ettus-fpga/zynq_fifo/zf_host_to_stream.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/new_rx_control.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_8sc_to_16sc.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/new_tx_control.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_12sc_to_16sc.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_32f_to_16sc.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_16sc_to_xxxx_chain.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/new_rx_framer.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/xxf_to_xxs.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/trigger_context_pkt.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_32f_to_16s.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/new_tx_deframer.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_16sc_to_8sc.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/float_to_iq.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_16sc_to_12sc.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/xxs_to_xxf.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_16s_to_32f.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_16sc_to_32f.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/tx_responder.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/iq_to_float.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_16s_to_8s.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_8s_to_16s.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/context_packet_gen.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita_200/chdr_xxxx_to_16sc_chain.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_cap_gen/catcodec_ddr_cmos.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_cap_gen/catgen_ddr_cmos.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_cap_gen/cat_output_lvds.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_cap_gen/cat_io_lvds.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_cap_gen/cat_input_lvds.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_cap_gen/cap_pattern_verifier.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_cap_gen/catcap_ddr_cmos.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_mux_select.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/monitor_axi_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_demux4.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_mux4.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo_cascade.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_filter_mux4.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo_flop2.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/fifo64_to_axi4lite.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo_bram.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_mux8.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_demux.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo_short.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo32_to_fifo64.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo_flop.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo_2clk.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo64_to_fifo32.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/shortfifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_packet_gate.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_mux.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_loopback.v" \
  "$ad_hdl_dir/library/ettus-fpga/fifo/axi_demux8.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita/packet_error_responder.v" \
  "$ad_hdl_dir/library/ettus-fpga/vita/flow_control_responder.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/src/lm32_adder.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/src/lm32_addsub.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/src/jtag_cores.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/src/lm32_logic_op.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/src/lm32_shifter.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/src/lm32_include.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/generated/lm32_allprofiles.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/platform/generic/lm32_multiplier.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_lm32/platform/generic/jtag_tap.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_onewire_master/sockit_owm.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_spi/spi_defines.v" \
  "$ad_hdl_dir/library/ettus-fpga/white_rabbit/wr_cores_v4_2/ip_cores/general-cores/modules/wishbone/wb_spi/timescale.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/eth_tasks.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/delay_line.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/simple_gemac_tx.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/crc.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/simple_gemac_wrapper.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/address_filter_promisc.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/axi64_to_ll8.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/mdio.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/flow_ctrl_rx.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/gmii_to_axis.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/flow_ctrl_tx.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/ll8_to_axi64.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/simple_gemac.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/ll8_to_txmac.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/simple_gemac_rx.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/address_filter.v" \
  "$ad_hdl_dir/library/ettus-fpga/simple_gemac/rxmac_to_ll8.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_moving_avg.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/vector_iir.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/mult_add.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_duc.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_sync.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cic_interpolate.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_vector_iir.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/mult_rc.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/fifo_srl.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_logpwr.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_eoseq.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_binmap.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_avg.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_wf_agg.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_rise_decay.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_maxhold.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_packetizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/delay.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/rng.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_line_mem.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/axi_logpwr.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fosphor/f15_histo_mem.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fft_shift.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/phase_accum.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_input_port.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/symbol_to_gray_bits.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_packet_mux.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_round_and_clip_complex.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/pfb_stage.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_tag_time.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/duc.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_eq.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_conv_encoder_qpsk.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/delay_type4.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/null_source.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/peak_detector.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/dds_freq_tune.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/delay_type3.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/complex_invert.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/agc_feed_forward.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/chdr_deframer_2clk.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cvita_hdr_parser.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/join_complex.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/sine_tone.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_wrapper.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_pipe_join.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_digital_gain.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/ram_to_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/fir_filter_slice.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/chdr_framer_2clk.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_window.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/complex_to_mag_approx.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/complex_to_magsq.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_pipe.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_skeleton.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/chdr_fifo_large.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_throttle.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/delay_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_invert_tb/pass_thru_and_invert.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_invert_tb/noc_block_invert.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/chdr_deframer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_axi_dma_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_round_and_clip.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/peak_finder.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_split_stream.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/keep_one_in_n.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cordic.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/file_source.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_bit_reduce.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/threshold_scaled.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/mult_add_rc.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/puncture.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_rate_change.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_export_io.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/ddc.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/file_sink.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/dds_timed.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_logpwr.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_file_source.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/periodic_framer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/mult.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_packet_resizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_clip_complex.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_fir_filter.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/schmidl_cox.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_round_complex.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_async_stream.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_responder.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cmd_pkt_proc.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/addsub.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_fft.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/pfb.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_replay.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_threshold.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cmul.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_pfb.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/const.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/const_sreg.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/ofdm_plateau_detector.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_packer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/one_tap_equalizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_addsub.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_axi_fifo_loopback.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_fosphor.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/chdr_framer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/split_complex.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_fir_filter.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cic_decimate.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cvita_hdr_modify.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_output_port.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_ddc.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_null_source_sink.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/split_stream.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_deserializer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_file_io.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_keep_one_in_n.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cordic_timed.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/split_stream_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_repeat.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_shell.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cvita_hdr_encoder.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/ofdm_constellation_demapper.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cadd.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/multiply.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_schmidl_cox.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_siggen.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/moving_sum.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_clip_unsigned.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_drop_partial_packet.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_clip.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_pipe_mac.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/window.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/delay_type2.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_debug.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/counter.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_block_ofdm_constellation_demapper.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_round.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/cvita_hdr_decoder.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/packet_resizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/conj.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/ofdm_peak_detector.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_serializer.v" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/axi_join.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/i2c_master_top.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/axi_stream_to_wb.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/i2c_master_defines.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/simple_uart_tx.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/settings_bus.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/i2c_master_bit_ctrl.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/settings_readback.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/simple_uart.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/wb_1master.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/simple_uart_rx.v" \
  "$ad_hdl_dir/library/ettus-fpga/wishbone/i2c_master_byte_ctrl.v" \
  "$ad_hdl_dir/library/ettus-fpga/wb_spi/rtl/verilog/spi_top.v" \
  "$ad_hdl_dir/library/ettus-fpga/wb_spi/rtl/verilog/spi_defines.v" \
  "$ad_hdl_dir/library/ettus-fpga/wb_spi/rtl/verilog/spi_clgen.v" \
  "$ad_hdl_dir/library/ettus-fpga/wb_spi/rtl/verilog/spi_top16.v" \
  "$ad_hdl_dir/library/ettus-fpga/wb_spi/rtl/verilog/spi_shift.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge_interface/xge_handshake.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge_interface/xge64_to_axi64.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge_interface/axi_count_packets_in_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge_interface/xge_mac_wrapper.v" \
  "$ad_hdl_dir/library/ettus-fpga/xge_interface/axi64_to_xge64.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/chdr_route_config.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/axis_ingress_vc_buff.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/mesh_2d_dor_router_multi_sw.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/mesh_2d_dor_router_single_sw.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/torus_2d_dor_router_multi_sw.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/axis_switch.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/torus_2d_dor_router_single_sw.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/axis_port_terminator.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/axis_ctrl_crossbar_2d_mesh.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/chdr_crossbar_nxn.v" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/chdr_xb_ingress_buff.v" \
  "$ad_hdl_dir/library/ettus-fpga/extramfifo/nobl_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/extramfifo/refill_randomizer.v" \
  "$ad_hdl_dir/library/ettus-fpga/extramfifo/nobl_if.v" \
  "$ad_hdl_dir/library/ettus-fpga/extramfifo/test_sram_if.v" \
  "$ad_hdl_dir/library/ettus-fpga/extramfifo/ext_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/control_200/cvita_uart.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/util_axis_resize/util_axis_resize.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/address_generator.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/request_generator.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/up_axi.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/splitter.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/src_axi_stream.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/2d_transfer.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/request_arb.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/axi_register_slice.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/axi_dmac.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/dest_fifo_inf.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/dest_axi_stream.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/response_generator.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/data_mover.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/sync_bits.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/src_axi_mm.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/response_handler.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/dest_axi_mm.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/axi_dmac/src_fifo_inf.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/util_axis_fifo/address_gray.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/util_axis_fifo/address_sync.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/util_axis_fifo/sync_gray.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/util_axis_fifo/util_axis_fifo.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/util_axis_fifo/sync_bits.v" \
  "$ad_hdl_dir/library/ettus-fpga/vivado_ipi/util_axis_fifo/address_gray_pipelined.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc_200/source_flow_control_legacy.v" \
  "$ad_hdl_dir/library/ettus-fpga/packet_proc_200/cvita_dest_lookup_legacy.v" \
  "$ad_hdl_dir/library/ettus-fpga/sim/fifo/axi_fifo_2clk_sim.v" \
  "$ad_hdl_dir/library/ettus-fpga/zpu/zpu_bootram.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/rx_dcoffset.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/add2_and_clip.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/rx_frontend.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/small_hb_dec.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/round_sd.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/add2.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/add2_reg.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/clip_reg.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/add2_and_round_reg.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/cic_int_shifter.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/sign_extend.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/cic_interp.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/round.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/round_reg.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/add2_and_clip_reg.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/hb47_int.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/acc.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/ddc_chain.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/clip.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/cic_decim.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/srl.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/cic_dec_shifter.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/duc_chain.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/cic_strober.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/cordic_z24.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/tx_frontend.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/hb_dec.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/small_hb_int.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/hb_interp.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/add2_and_round.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/cordic_stage.v" \
  "$ad_hdl_dir/library/ettus-fpga/dsp/add_then_mac.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio/rx_frontend_gen3.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio/rx_control_gen3.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio/radio_datapath_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio/tx_frontend_gen3.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio/noc_block_radio_core.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio/db_control.v" \
  "$ad_hdl_dir/library/ettus-fpga/radio/tx_control_gen3.v" \
  "$ad_hdl_dir/library/ettus-fpga/io_port2/LvFpga_Chinch_Interface.vh" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/noc_shell_regs.vh" \
  "$ad_hdl_dir/library/ettus-fpga/rfnoc/data_types.vh" \
  "$ad_hdl_dir/library/ettus-fpga/crossbar/mesh_node_mapping.vh" \
  "$ad_hdl_dir/library/ettus-fpga/radio/radio_core_regs.vh"]

set_property is_enabled false [get_files  *system_sys_ps7_0.xdc]
adi_project_run pluto
# source $ad_hdl_dir/library/axi_ad9361/axi_ad9361_delay.tcl

